In [1]:
from mxnet import autograd, nd

/Users/wonji/anaconda3/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters


In [2]:
x = nd.arange(4).reshape((4,1))

In [3]:
x


[[0.]
 [1.]
 [2.]
 [3.]]
<NDArray 4x1 @cpu(0)>

# 1. 하나의 with 절에서 돌리기 

In [4]:
x.attach_grad()

In [5]:
with autograd.record():
    y=nd.dot(x,x.T)
# with autograd.record():
    z=y*x

In [6]:
y.attach_grad()

In [7]:
z.backward()

In [8]:
y.backward(y.grad)

In [9]:
x.grad


[[14.]
 [26.]
 [38.]
 [50.]]
<NDArray 4x1 @cpu(0)>

In [17]:
y.grad


[[0. 0. 0. 0.]
 [1. 1. 1. 1.]
 [2. 2. 2. 2.]
 [3. 3. 3. 3.]]
<NDArray 4x4 @cpu(0)>

# 2. with 절 나눠서 돌리기 

In [10]:
x.attach_grad()

In [11]:
with autograd.record():
    y=nd.dot(x,x.T)

In [12]:
y.attach_grad()
with autograd.record():
    z=y*x

In [13]:
z.backward()

In [14]:
y.backward(y.grad)

In [15]:
x.grad


[[ 0.]
 [ 6.]
 [12.]
 [18.]]
<NDArray 4x1 @cpu(0)>

In [16]:
y.grad


[[0. 0. 0. 0.]
 [1. 1. 1. 1.]
 [2. 2. 2. 2.]
 [3. 3. 3. 3.]]
<NDArray 4x4 @cpu(0)>

## 예시 #1

In [42]:
x.attach_grad()

In [43]:
with autograd.record():
    y=x*x

In [44]:
y.backward()

In [45]:
x.grad


[[0.]
 [2.]
 [4.]
 [6.]]
<NDArray 4x1 @cpu(0)>

## 예시 #2

In [49]:
x.attach_grad()
with autograd.record():
    y=nd.dot(x,x.T)
    
y.backward()

In [50]:
x.grad 


[[12.]
 [12.]
 [12.]
 [12.]]
<NDArray 4x1 @cpu(0)>